/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesteWebhookRouteImport } from './routes/teste-webhook'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PreCadastroRouteImport } from './routes/pre-cadastro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppReimbursementsRouteImport } from './routes/_app.reimbursements'
import { Route as AppPolicyRouteImport } from './routes/_app.policy'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppNfeRouteImport } from './routes/_app.nfe'
import { Route as AppExpensesIndexRouteImport } from './routes/_app.expenses.index'
import { Route as ApiPublicReimbursementsRouteImport } from './routes/api/public/reimbursements'
import { Route as ApiPublicEvolutionRouteImport } from './routes/api/public/evolution'
import { Route as ApiPublicDespesasRouteImport } from './routes/api/public/despesas'
import { Route as AppExpensesIdRouteImport } from './routes/_app.expenses.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksHealthCheckRouteImport } from './routes/api/public/hooks/health-check'

const TesteWebhookRoute = TesteWebhookRouteImport.update({
  id: '/teste-webhook',
  path: '/teste-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PreCadastroRoute = PreCadastroRouteImport.update({
  id: '/pre-cadastro',
  path: '/pre-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReimbursementsRoute = AppReimbursementsRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRoute = AppPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppNfeRoute = AppNfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicReimbursementsRoute = ApiPublicReimbursementsRouteImport.update({
  id: '/api/public/reimbursements',
  path: '/api/public/reimbursements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvolutionRoute = ApiPublicEvolutionRouteImport.update({
  id: '/api/public/evolution',
  path: '/api/public/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDespesasRoute = ApiPublicDespesasRouteImport.update({
  id: '/api/public/despesas',
  path: '/api/public/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExpensesIdRoute = AppExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHealthCheckRoute =
  ApiPublicHooksHealthCheckRouteImport.update({
    id: '/api/public/hooks/health-check',
    path: '/api/public/hooks/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste-webhook': typeof TesteWebhookRoute
  '/nfe': typeof AppNfeRoute
  '/overview': typeof AppOverviewRoute
  '/policy': typeof AppPolicyRoute
  '/reimbursements': typeof AppReimbursementsRoute
  '/reports': typeof AppReportsRoute
  '/users': typeof AppUsersRoute
  '/expenses/$id': typeof AppExpensesIdRoute
  '/api/public/despesas': typeof ApiPublicDespesasRoute
  '/api/public/evolution': typeof ApiPublicEvolutionRoute
  '/api/public/reimbursements': typeof ApiPublicReimbursementsRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste-webhook': typeof TesteWebhookRoute
  '/nfe': typeof AppNfeRoute
  '/overview': typeof AppOverviewRoute
  '/policy': typeof AppPolicyRoute
  '/reimbursements': typeof AppReimbursementsRoute
  '/reports': typeof AppReportsRoute
  '/users': typeof AppUsersRoute
  '/expenses/$id': typeof AppExpensesIdRoute
  '/api/public/despesas': typeof ApiPublicDespesasRoute
  '/api/public/evolution': typeof ApiPublicEvolutionRoute
  '/api/public/reimbursements': typeof ApiPublicReimbursementsRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste-webhook': typeof TesteWebhookRoute
  '/_app/nfe': typeof AppNfeRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/policy': typeof AppPolicyRoute
  '/_app/reimbursements': typeof AppReimbursementsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/expenses/$id': typeof AppExpensesIdRoute
  '/api/public/despesas': typeof ApiPublicDespesasRoute
  '/api/public/evolution': typeof ApiPublicEvolutionRoute
  '/api/public/reimbursements': typeof ApiPublicReimbursementsRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pre-cadastro'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/teste-webhook'
    | '/nfe'
    | '/overview'
    | '/policy'
    | '/reimbursements'
    | '/reports'
    | '/users'
    | '/expenses/$id'
    | '/api/public/despesas'
    | '/api/public/evolution'
    | '/api/public/reimbursements'
    | '/expenses/'
    | '/api/public/hooks/health-check'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pre-cadastro'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/teste-webhook'
    | '/nfe'
    | '/overview'
    | '/policy'
    | '/reimbursements'
    | '/reports'
    | '/users'
    | '/expenses/$id'
    | '/api/public/despesas'
    | '/api/public/evolution'
    | '/api/public/reimbursements'
    | '/expenses'
    | '/api/public/hooks/health-check'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/pre-cadastro'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/teste-webhook'
    | '/_app/nfe'
    | '/_app/overview'
    | '/_app/policy'
    | '/_app/reimbursements'
    | '/_app/reports'
    | '/_app/users'
    | '/_app/expenses/$id'
    | '/api/public/despesas'
    | '/api/public/evolution'
    | '/api/public/reimbursements'
    | '/_app/expenses/'
    | '/api/public/hooks/health-check'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PreCadastroRoute: typeof PreCadastroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TesteWebhookRoute: typeof TesteWebhookRoute
  ApiPublicDespesasRoute: typeof ApiPublicDespesasRoute
  ApiPublicEvolutionRoute: typeof ApiPublicEvolutionRoute
  ApiPublicReimbursementsRoute: typeof ApiPublicReimbursementsRoute
  ApiPublicHooksHealthCheckRoute: typeof ApiPublicHooksHealthCheckRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teste-webhook': {
      id: '/teste-webhook'
      path: '/teste-webhook'
      fullPath: '/teste-webhook'
      preLoaderRoute: typeof TesteWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-cadastro': {
      id: '/pre-cadastro'
      path: '/pre-cadastro'
      fullPath: '/pre-cadastro'
      preLoaderRoute: typeof PreCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reimbursements': {
      id: '/_app/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof AppReimbursementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy': {
      id: '/_app/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof AppPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nfe': {
      id: '/_app/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof AppNfeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/reimbursements': {
      id: '/api/public/reimbursements'
      path: '/api/public/reimbursements'
      fullPath: '/api/public/reimbursements'
      preLoaderRoute: typeof ApiPublicReimbursementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution': {
      id: '/api/public/evolution'
      path: '/api/public/evolution'
      fullPath: '/api/public/evolution'
      preLoaderRoute: typeof ApiPublicEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/despesas': {
      id: '/api/public/despesas'
      path: '/api/public/despesas'
      fullPath: '/api/public/despesas'
      preLoaderRoute: typeof ApiPublicDespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/expenses/$id': {
      id: '/_app/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof AppExpensesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health-check': {
      id: '/api/public/hooks/health-check'
      path: '/api/public/hooks/health-check'
      fullPath: '/api/public/hooks/health-check'
      preLoaderRoute: typeof ApiPublicHooksHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppNfeRoute: typeof AppNfeRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPolicyRoute: typeof AppPolicyRoute
  AppReimbursementsRoute: typeof AppReimbursementsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppExpensesIdRoute: typeof AppExpensesIdRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNfeRoute: AppNfeRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPolicyRoute: AppPolicyRoute,
  AppReimbursementsRoute: AppReimbursementsRoute,
  AppReportsRoute: AppReportsRoute,
  AppUsersRoute: AppUsersRoute,
  AppExpensesIdRoute: AppExpensesIdRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PreCadastroRoute: PreCadastroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TesteWebhookRoute: TesteWebhookRoute,
  ApiPublicDespesasRoute: ApiPublicDespesasRoute,
  ApiPublicEvolutionRoute: ApiPublicEvolutionRoute,
  ApiPublicReimbursementsRoute: ApiPublicReimbursementsRoute,
  ApiPublicHooksHealthCheckRoute: ApiPublicHooksHealthCheckRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
